### ISSUE TITLE
Logomarca

### ISSUE THREAD

**Issue by IgorDePaula** [angularjsbr/brainstorming#1]
Vamos discutir aqui a logomarca?

**Comment by leidsoncruz** [comment]
Vamos sim, você tem algo em mente ?

**Comment by IgorDePaula** [comment]
Pensei em trocar as cores da logomarca do angular para cores em verde e
amarelo, mas acho que isso vai contra as leis de direitos autorais....

Em 14 de abril de 2015 10:36, Leidson Dias notifications@github.com
escreveu:

**Comment by leidsoncruz** [comment]
Vi um muito irado segue em anexo, deste evento aqui:
http://devshopbrasil.github.io/devshopbrasil/

Em 14 de abril de 2015 10:38, Igor C. de Paula notifications@github.com
escreveu:

> Pensei em trocar as cores da logomarca do angular para cores em verde e
> amarelo, mas acho que isso vai contra as leis de direitos autorais....
> 
> Em 14 de abril de 2015 10:36, Leidson Dias notifications@github.com
> escreveu:
> 
> > Vamos sim, você tem algo em mente ?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-92841863
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-92845099
> .

## 

Leidson Dias | http://leidsondias.com.br/
Graduado em Análise e Desenvolvimento de Sistemas - Estácio IDez

**Comment by IgorDePaula** [comment]
Mal comecamos com a logomarca, e ja quer vender camiseta? C eh rapido
hein...kkk

brincadeira, mas se existe uma versao do escudo do angular em versao
europeia (eu nem tinha me tocado na ngeuro), acredito q nao ha empecilhos
para uma versao br.

Em 14 de abril de 2015 11:00, Leidson Dias notifications@github.com
escreveu:

**Comment by leidsoncruz** [comment]
kkkkk essa para mim já é  BR. Amarela, azul e verde

Em 14 de abril de 2015 11:05, Igor C. de Paula notifications@github.com
escreveu:

> Mal comecamos com a logomarca, e ja quer vender camiseta? C eh rapido
> hein...kkk
> 
> brincadeira, mas se existe uma versao do escudo do angular em versao
> europeia (eu nem tinha me tocado na ngeuro), acredito q nao ha empecilhos
> para uma versao br.
> 
> Em 14 de abril de 2015 11:00, Leidson Dias notifications@github.com
> escreveu:
> 
> > Vi um muito irado segue em anexo, deste evento aqui:
> > http://devshopbrasil.github.io/devshopbrasil/
> > 
> > Em 14 de abril de 2015 10:38, Igor C. de Paula <notifications@github.com
> > 
> > escreveu:
> > 
> > > Pensei em trocar as cores da logomarca do angular para cores em verde e
> > > amarelo, mas acho que isso vai contra as leis de direitos autorais....
> > > 
> > > Em 14 de abril de 2015 10:36, Leidson Dias notifications@github.com
> > > escreveu:
> > > 
> > > > Vamos sim, você tem algo em mente ?
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-92841863
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-92845099
> > 
> > > .
> > 
> > ## 
> > 
> > Leidson Dias | http://leidsondias.com.br/
> > Graduado em Análise e Desenvolvimento de Sistemas - Estácio IDez
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-92862356
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-92864376
> .

## 

Leidson Dias | http://leidsondias.com.br/
Graduado em Análise e Desenvolvimento de Sistemas - Estácio IDez

**Comment by IgorDePaula** [comment]
E vermelho?

Nao esta chrome demais nao?

Alem disso tem q verificar se ela nao eh usada em nenhum outro lugar...

Em 14 de abril de 2015 11:15, Leidson Dias notifications@github.com
escreveu:

**Comment by leidsoncruz** [comment]
Bom, lembrando que aqui não tem fins comerciais não vejo o problema de usar
ela. Eu particulamente achei muito boa ela, caso concordem usamos x))

Em 14 de abril de 2015 11:21, Igor C. de Paula notifications@github.com
escreveu:

> E vermelho?
> 
> Nao esta chrome demais nao?
> 
> Alem disso tem q verificar se ela nao eh usada em nenhum outro lugar...
> 
> Em 14 de abril de 2015 11:15, Leidson Dias notifications@github.com
> escreveu:
> 
> > kkkkk essa para mim já é BR. Amarela, azul e verde
> > 
> > Em 14 de abril de 2015 11:05, Igor C. de Paula <notifications@github.com
> > 
> > escreveu:
> > 
> > > Mal comecamos com a logomarca, e ja quer vender camiseta? C eh rapido
> > > hein...kkk
> > > 
> > > brincadeira, mas se existe uma versao do escudo do angular em versao
> > > europeia (eu nem tinha me tocado na ngeuro), acredito q nao ha
> > > empecilhos
> > > para uma versao br.
> > > 
> > > Em 14 de abril de 2015 11:00, Leidson Dias notifications@github.com
> > > escreveu:
> > > 
> > > > Vi um muito irado segue em anexo, deste evento aqui:
> > > > http://devshopbrasil.github.io/devshopbrasil/
> > > > 
> > > > Em 14 de abril de 2015 10:38, Igor C. de Paula <
> > > > notifications@github.com
> > > > 
> > > > escreveu:
> > > > 
> > > > > Pensei em trocar as cores da logomarca do angular para cores em
> > > > > verde e
> > > > > amarelo, mas acho que isso vai contra as leis de direitos
> > > > > autorais....
> > > > > 
> > > > > Em 14 de abril de 2015 10:36, Leidson Dias <
> > > > > notifications@github.com
> > > > > 
> > > > > escreveu:
> > > > > 
> > > > > > Vamos sim, você tem algo em mente ?
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > 
> > https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-92841863
> > 
> > > > > > .
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > 
> > https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-92845099
> > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Leidson Dias | http://leidsondias.com.br/
> > > > Graduado em Análise e Desenvolvimento de Sistemas - Estácio IDez
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-92862356
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-92864376
> > 
> > > .
> > 
> > ## 
> > 
> > Leidson Dias | http://leidsondias.com.br/
> > Graduado em Análise e Desenvolvimento de Sistemas - Estácio IDez
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-92867720
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-92869621
> .

## 

Leidson Dias | http://leidsondias.com.br/
Graduado em Análise e Desenvolvimento de Sistemas - Estácio IDez

**Comment by IgorDePaula** [comment]
blz.

Em 14 de abril de 2015 11:33, Leidson Dias notifications@github.com
escreveu:

**Comment by leidsoncruz** [comment]
Que que vocês acham ?

**Comment by IgorDePaula** [comment]
Pessoal, vamos votar na logo.

![Imagem para logomarca do angularjsbr ](
http://devshopbrasil.github.io/devshopbrasil/images/angularjs2.png)

Digam 'S', para sim e 'N' para nao.

Vamos utilizar este tipo de votação para mais tarde criarmos uma aplicacao
em angular para apurar a votacao...

2015-04-14 13:52 GMT-03:00 Leidson Dias <notifications@github.com>:

**Comment by IgorDePaula** [comment]
Pessoal, vamos votar na logo.

![Imagem para logomarca do angularjsbr](http://devshopbrasil.github.io/devshopbrasil/images/angularjs2.png)

Digam 'S', para sim e 'N' para nao.

Vamos utilizar este tipo de votação para mais tarde criarmos uma aplicacao
em angular para apurar a votacao...

**Comment by leidsoncruz** [comment]
S

**Comment by danielpereirabp** [comment]
S

**Comment by FernandoCagale** [comment]
S

**Comment by adell** [comment]
S

**Comment by IgorDePaula** [comment]
Galera eu criei uma página (oohh, é em angular) para acompanhar-mos a votação da logomarca.

http://angularjsbr.github.io/

**Comment by jhosefmarks** [comment]
IgorDePaula, a página não está funcionando

Meu voto 'S'

**Comment by IgorDePaula** [comment]
Por favor, defina "nao esta funcionando": nao carregou o conteudo, nao
carregou os scripts, o que houve?

O voto será computado, com apenas N ou S no comentario, qualquer outra
coisa, ele nao sera computado, justamente para nao juntar comentarios que
nao sao votos, permitindo que o topico sirva pra comentar e votar ao mesmo
tempo.

Em 15 de abril de 2015 13:46, jhosefmarks notifications@github.com
escreveu:

**Comment by FernandoCagale** [comment]
Acho que a maioria vai escolher essa!

**Comment by IgorDePaula** [comment]
Eu vou tentar desenhar outra, nao sei..eu nao sou bom designer, sou melhor
programador.

@jhosefmarks, corrigi algo que poderia impedir de carregar uma biblioteca,
por favor tente novamente.

Em 15 de abril de 2015 13:54, Cagale notifications@github.com escreveu:

**Comment by jhosefmarks** [comment]
@IgorDePaula Está aparecendo assim o resultado da página

Sim ( {{sim}} voto(s) )
Não ( {{nao}} voto(s) )

**Comment by jhosefmarks** [comment]
S

**Comment by FernandoCagale** [comment]
Acabei de visualizar e está aparecendo normal aqui!

**Comment by adell** [comment]
Para mim tb!

2015-04-15 14:18 GMT-03:00 Cagale notifications@github.com:

> Acabei de visualizar e está aparecendo normal aqui!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-93491010
> .

## 

Porque Dele, por Ele, para Ele são todas as coisas;
a Ele a glória eternamente.

## Amém.

**Comment by leidsoncruz** [comment]
Refused to execute script from '
https://raw.githubusercontent.com/angular/bower-angular-animate/master/angular-animate.min.js'
because its MIME type ('text/plain') is not executable, and strict MIME
type checking is enabled.
(index):1 Refused to execute script from '
https://raw.githubusercontent.com/angular/bower-angular-aria/master/angular-aria.min.js'
because its MIME type ('text/plain') is not executable, and strict MIME
type checking is enabled.
angular.js:4138 Uncaught Error: [$injector:modulerr] Failed to instantiate
module Friend due to:
Error: [$injector:modulerr] Failed to instantiate module ngMaterial due to:
Error: [$injector:modulerr] Failed to instantiate module ngAnimate due to:
Error: [$injector:nomod] Module 'ngAnimate' is not available! You either
misspelled the module name or forgot to load it. If registering a module
ensure that you specify the dependencies as the second argument.

2015-04-15 14:17 GMT-03:00 jhosefmarks notifications@github.com:

> S
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-93490871
> .

## 

Leidson Dias | http://leidsondias.com.br/
Graduado em Análise e Desenvolvimento de Sistemas - Estácio IDez

**Comment by leidsoncruz** [comment]
Só funcionando no firefox, no chrome da o erro acima :}

2015-04-15 14:18 GMT-03:00 Leidson Dias leidson89@gmail.com:

> Refused to execute script from '
> https://raw.githubusercontent.com/angular/bower-angular-animate/master/angular-animate.min.js'
> because its MIME type ('text/plain') is not executable, and strict MIME
> type checking is enabled.
> (index):1 Refused to execute script from '
> https://raw.githubusercontent.com/angular/bower-angular-aria/master/angular-aria.min.js'
> because its MIME type ('text/plain') is not executable, and strict MIME
> type checking is enabled.
> angular.js:4138 Uncaught Error: [$injector:modulerr] Failed to instantiate
> module Friend due to:
> Error: [$injector:modulerr] Failed to instantiate module ngMaterial due to:
> Error: [$injector:modulerr] Failed to instantiate module ngAnimate due to:
> Error: [$injector:nomod] Module 'ngAnimate' is not available! You either
> misspelled the module name or forgot to load it. If registering a module
> ensure that you specify the dependencies as the second argument.
> 
> 2015-04-15 14:17 GMT-03:00 jhosefmarks notifications@github.com:
> 
> > S
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-93490871
> > .
> 
> ## 
> 
> Leidson Dias | http://leidsondias.com.br/
> Graduado em Análise e Desenvolvimento de Sistemas - Estácio IDez

## 

Leidson Dias | http://leidsondias.com.br/
Graduado em Análise e Desenvolvimento de Sistemas - Estácio IDez

**Comment by FernandoCagale** [comment]
Verdade no chrome não funfa mesmo!

**Comment by IgorDePaula** [comment]
Corrigido.

2015-04-15 14:20 GMT-03:00 Cagale notifications@github.com:

**Comment by leidsoncruz** [comment]
Boa garoto!! Tenta postar tua logo até amanhã para fecharmos a votação
domingo

2015-04-15 14:41 GMT-03:00 Igor C. de Paula notifications@github.com:

> Corrigido.
> 
> 2015-04-15 14:20 GMT-03:00 Cagale notifications@github.com:
> 
> > Verdade no chrome não funfa mesmo!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-93491541
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-93496122
> .

## 

Leidson Dias | http://leidsondias.com.br/
Graduado em Análise e Desenvolvimento de Sistemas - Estácio IDez

**Comment by IgorDePaula** [comment]
Perdao, estou sem as ferramentas, eu ia tentar fazer algo no fds, mas entao
deixa pra la.

Em 15 de abril de 2015 14:49, Leidson Dias notifications@github.com
escreveu:

**Comment by leidsoncruz** [comment]
Para tentar agilizarmos logo e matarmos essa pendência sacou?
Vamos focar agora na brainstorm

Em 15 de abril de 2015 14:51, Igor C. de Paula notifications@github.com
escreveu:

> Perdao, estou sem as ferramentas, eu ia tentar fazer algo no fds, mas entao
> deixa pra la.
> 
> Em 15 de abril de 2015 14:49, Leidson Dias notifications@github.com
> escreveu:
> 
> > Boa garoto!! Tenta postar tua logo até amanhã para fecharmos a votação
> > domingo
> > 
> > 2015-04-15 14:41 GMT-03:00 Igor C. de Paula notifications@github.com:
> > 
> > > Corrigido.
> > > 
> > > 2015-04-15 14:20 GMT-03:00 Cagale notifications@github.com:
> > > 
> > > > Verdade no chrome não funfa mesmo!
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-93491541
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-93496122
> > 
> > > .
> > 
> > ## 
> > 
> > Leidson Dias | http://leidsondias.com.br/
> > Graduado em Análise e Desenvolvimento de Sistemas - Estácio IDez
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-93499208
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/angularjsbr/brainstorming/issues/1#issuecomment-93499789
> .

## 

Leidson Dias | http://leidsondias.com.br/
Graduado em Análise e Desenvolvimento de Sistemas - Estácio IDez

**Comment by IgorDePaula** [comment]
Sim, eu entendi perfeitamente..Depois vou ver se faço a mesma coisa com o
brainstorm....o lance da votacao...seria ideal alguem mecher la e computar
quem nao votou, evitar que a mesma pessoa vote mais de uma vez...

Em 15 de abril de 2015 14:57, Leidson Dias notifications@github.com
escreveu:

**Comment by jhosefmarks** [comment]
@IgorDePaula  agora sim!!!.

**Comment by samuelcastro** [comment]
S

**Comment by gufigueiredo** [comment]
S

**Comment by leidsoncruz** [comment]
Bom, logo marca definida. Vamos aos issues do que fazer.
